"""Pinned package installation, without relying on Apio's changing remote defaults."""
from lab2_intro import paras,steps,terminal


def programmer_install(d):
    d.frame('openFPGALoader 설치 · Ubuntu',paras('WSL Ubuntu 터미널에서 실행한다. 아래 설치는 Windows PowerShell 명령이 아니다.')+terminal('sudo apt update','sudo apt install openfpgaloader usbutils','openFPGALoader --help','openFPGALoader --list-cables')+r'\href{https://trabucayre.github.io/openFPGALoader/guide/install.html}{공식 운영체제별 설치 안내}')
    d.frame('openFPGALoader 설치 · macOS',paras('Apple Silicon Mac은 macOS 터미널에서 아래 명령을 사용한다. Ubuntu 사용자는 이 장을 건너뛴다.')+terminal('brew install openfpgaloader','openFPGALoader --help','openFPGALoader --list-cables')+paras('Homebrew가 먼저 설치되어 있어야 한다. 이 교안의 실행 검증은 WSL Linux이며 macOS 실측 기록은 아니다.')+r'\href{https://trabucayre.github.io/openFPGALoader/guide/install.html}{공식 macOS 설치 안내}')
    d.frame('WSL에 JTAG 전달 · Windows 준비',paras('Windows PowerShell에서 실행한다. WSL 2 Ubuntu 터미널도 열어 둔다. 이미 usbipd-win 5 이상이 설치되어 있으면 설치 명령은 건너뛴다.')+terminal('winget install --interactive --exact dorssel.usbipd-win','usbipd --version','usbipd list')+paras('목록에서 실습 보드의 USB JTAG 장치를 찾는다. 다음 장의 MY_BUSID를 그 행의 BUSID로 바꾼다.')+r'\href{https://learn.microsoft.com/en-us/windows/wsl/connect-usb}{Microsoft WSL USB 연결 안내}')
    d.frame('WSL에 JTAG 전달 · 연결',paras('관리자 PowerShell에서 한 번 공유한 뒤, 일반 PowerShell에서 연결한다. MY_BUSID에는 앞에서 확인한 BUSID를 넣는다.')+terminal('usbipd bind --busid MY_BUSID','usbipd attach --wsl --busid MY_BUSID','usbipd list')+paras('bind만 관리자 권한이 필요하다. 연결 상태가 Attached인지 확인한다. WSL에 연결한 동안 Windows 프로그램은 해당 USB 장치를 사용할 수 없다.'))
    d.frame('WSL에서 장치 확인과 반환',paras('WSL Ubuntu 터미널에서 장치가 보이는지 먼저 확인한다.')+terminal('lsusb','openFPGALoader --list-cables','openFPGALoader --detect')+paras('권한 오류는 공식 udev 설정 안내를 확인한다. FPGA 탐지가 실패하면 bit 기록으로 진행하지 않는다. 실습이 끝나면 Windows PowerShell에서 반환한다.')+terminal('usbipd detach --busid MY_BUSID')+r'\href{https://trabucayre.github.io/openFPGALoader/guide/install.html\#udev-rules}{공식 USB 접근 권한 안내}')


def install(d):
    d.frame('CLI 실행 환경 선택', paras('Windows는 WSL Linux x86-64 터미널에서 실행한다. Apple Silicon Mac은 macOS 터미널과 darwin-arm64 패키지를 사용한다.', '아래 명령은 같은 터미널에서 순서대로 실행한다. Python 3·Git·curl·tar를 먼저 확인한다.')+terminal('python3 --version','git --version','curl --version','tar --version','uname -s -m'))
    d.frame('고정 릴리스와 설치 폴더', terminal('platform=linux-x86-64','tools="$HOME/fpga-cli/tools-lab2-202608"','mkdir -p "$tools/oss-cad-suite" "$tools/openxc7"')+paras('WSL x86-64는 위 platform을 쓴다. Apple Silicon Mac에서는 첫 줄을 platform=darwin-arm64로 바꾼다.', 'OSS CAD Suite 2026-08-19와 openXC7 2026-08-20을 직접 받는다. apio packages install은 원격의 최신 요구 버전을 따르므로 이 교안의 고정 버전 설치에 사용하지 않는다.'))
    d.frame('OSS CAD Suite 고정 패키지', terminal('base=https://github.com/fpgawars/tools-oss-cad-suite','base="$base/releases/download/2026-08-19"','file="apio-oss-cad-suite-$platform-20260819.tgz"','curl --fail --location "$base/$file" -o "$tools/oss.tgz"','tar -xzf "$tools/oss.tgz" -C "$tools/oss-cad-suite"')+r'\href{https://github.com/fpgawars/tools-oss-cad-suite/releases/tag/2026-08-19}{공식 OSS CAD Suite 고정 릴리스}\par\vspace{0.2cm}'+paras('다운로드가 실패하면 다음 줄을 실행하지 않는다. 압축 내부의 bin·lib 등은 지정한 설치 폴더 바로 아래에 풀린다.'))
    d.frame('openXC7 고정 패키지', terminal('base=https://github.com/fpgawars/tools-openxc7','base="$base/releases/download/2026-08-20"','file="apio-openxc7-$platform-20260820.tgz"','curl --fail --location "$base/$file" -o "$tools/openxc7.tgz"','tar -xzf "$tools/openxc7.tgz" -C "$tools/openxc7"')+r'\href{https://github.com/fpgawars/tools-openxc7/releases/tag/2026-08-20}{공식 openXC7 고정 릴리스}\par\vspace{0.2cm}'+paras('이 패키지는 nextpnr-xilinx·프레임 변환·bitread를 제공한다. 다른 FPGA의 part 데이터로 대체하지 않는다.'))
    d.frame('같은 터미널에서 도구 경로 설정', terminal('export PATH="$tools/oss-cad-suite/bin:$tools/openxc7/bin:$PATH"','yosys -V','nextpnr-xilinx --version','iverilog -V','vvp -V')+paras('검증 기록의 Yosys는 0.63+173 (66306a8ca), nextpnr는 68aeeb3이다. 다르면 PATH에서 어떤 실행 파일이 먼저 선택됐는지 확인한다.', '새 터미널을 열면 tools 변수와 export PATH를 다시 실행한다. 다운로드·압축 해제까지 매번 반복하지 않는다.'))
