set project_dir [file dirname [file normalize [info script]]]
create_project lab1_integrated [file join $project_dir vivado] -part xc7s75fgga484-1 -force
set_property target_language Verilog [current_project]
add_files [file normalize [file join $project_dir {../../common/rtl/logic_gate.v}]]
add_files [file normalize [file join $project_dir {../../common/rtl/half_adder.v}]]
add_files [file normalize [file join $project_dir {../../common/rtl/full_adder.v}]]
add_files [file normalize [file join $project_dir {../../common/rtl/adder_4bit.v}]]
add_files [file normalize [file join $project_dir {../../common/rtl/sub_4bit.v}]]
add_files [file normalize [file join $project_dir {../../common/rtl/compare_4.v}]]
add_files [file normalize [file join $project_dir {../../common/rtl/mux_4x1.v}]]
add_files [file normalize [file join $project_dir {../../common/rtl/demux_1x8.v}]]
add_files [file normalize [file join $project_dir {../../common/rtl/encoder8x3.v}]]
add_files [file normalize [file join $project_dir {../../common/rtl/decoder3x8.v}]]
add_files [file normalize [file join $project_dir {../../common/rtl/seg_decoder.v}]]
add_files [file normalize [file join $project_dir {../../common/rtl/button_onepulse.v}]]
add_files [file normalize [file join $project_dir {../../common/rtl/lcd_modes.v}]]
add_files [file normalize [file join $project_dir {../../common/rtl/lab1_integrated.v}]]
add_files -fileset sim_1 [file normalize [file join $project_dir {../../common/tb/tb_lab1_integrated.sv}]]
add_files -fileset constrs_1 [file normalize [file join $project_dir {../../common/constraints/lab1_integrated.xdc}]]
set_property top lab1_integrated [get_filesets sources_1]
set_property top tb_lab1_integrated [get_filesets sim_1]
set_property xsim.simulate.runtime all [get_filesets sim_1]
update_compile_order -fileset sources_1
update_compile_order -fileset sim_1
close_project
